import os
import logging
from typing import Literal
from pydantic import BaseModel, Field
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, ToolMessage, HumanMessage


from .state import AgentState
from .prompts import SUPERVISOR_PROMPT, CONVERSATIONAL_PROMPT, RAG_PROMPT, TRANSACTIONAL_PROMPT, OUT_OF_BOUNDS_PROMPT
from .tools.portfolio import navigate_website, retrieve_portfolio_info, execute_loan_prediction

# Configure the terminal logger
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.1)

rag_llm = ChatOpenAI(model="gpt-4o-mini", temperature=0).bind_tools([retrieve_portfolio_info])

class RouteSchema(BaseModel):
    next_node: Literal["rag_agent", "transactional_agent", "conversational_agent", "OUT_OF_BOUNDS"] = Field(...)

supervisor_llm = llm.with_structured_output(RouteSchema)

async def supervisor_node(state: AgentState):
    logger.info("🟢 ACTIVATED: Supervisor Node -> Analyzing user intent...")
    
    # --- 💾 MONGODB LOGGING TRACE ---
    total_messages = len(state["messages"])
    logger.info(f"💾 MONGODB MEMORY: Loaded {total_messages} total message(s) from database.")
    
    if total_messages > 1:
        logger.info("🕒 HISTORY TRACE (Previous 3 messages):")
        previous_messages = state["messages"][-4:-1] 
        for msg in previous_messages:
            role = "USER" if msg.type == "user" else ("AI" if msg.type == "ai" else "TOOL")
            content = msg.content
            if len(content) > 75:
                content = content[:75] + "..."
            logger.info(f"   -> [{role}]: {content}")
    else:
        logger.info("🕒 HISTORY TRACE: 0 previous messages. This is a brand new conversation.")
    # ------------------------------------
    
    # 1. Grab the exact string the user just typed from your new state variable
    user_input = state.get("current_user_input", "")

    # 2. THE HANDOFF INTERCEPT: If the RAG agent failed and left a guardrail message,
    # instantly pass it to OUT_OF_BOUNDS without even asking the LLM.
    last_message = state["messages"][-1]
    if last_message.type == "tool" and "GUARDRAIL_TRIGGERED" in last_message.content:
        logger.info("🔀 ROUTING: RAG Guardrail detected. Manually passing work to -> [OUT_OF_BOUNDS]")
        return {"next_agent": "OUT_OF_BOUNDS"}

    # 3. Combine the system prompt with ONLY the exact user input
    messages = [SystemMessage(content=SUPERVISOR_PROMPT), HumanMessage(content=user_input)]
    
    decision = await supervisor_llm.ainvoke(messages)
    
    logger.info(f"🔀 ROUTING: Supervisor decided to route to -> [{decision.next_node}]")
    return {"next_agent": decision.next_node}

async def conversational_agent(state: AgentState):
    logger.info("🟢 ACTIVATED: Conversational Agent -> Processing small talk/navigation...")
    agent = llm.bind_tools([navigate_website])
    response = await agent.ainvoke([SystemMessage(content=CONVERSATIONAL_PROMPT)] + state["messages"])
    return {"messages": [response]}

async def rag_agent(state: AgentState):
    logger.info("🟢 ACTIVATED: RAG Agent -> Preparing to search portfolio context...")
    
    # Extract the exact string the user typed from the state
    user_input = state.get("current_user_input", "")
    
    # 1. Ask the RAG LLM to analyze the request WITH the RAG System Prompt
    messages = [SystemMessage(content=RAG_PROMPT)] + state["messages"]
    response = await rag_llm.ainvoke(messages)
    
    # 2. Check if the LLM decided to use the Pinecone tool
    if hasattr(response, 'tool_calls') and len(response.tool_calls) > 0:
        tool_call = response.tool_calls[0]
        
        if tool_call["name"] == "retrieve_portfolio_info":
            logger.info(f"🛠️ RAG Agent executing tool: {tool_call['name']}")
            
            # 1. Extract the optimized query generated by the LLM
            optimized_query = tool_call["args"]["query"]
            logger.info(f"🔎 OPTIMIZED SEARCH: LLM translated input to: '{optimized_query}'")
            
            # 2. Execute Pinecone using the optimized query!
            tool_output = retrieve_portfolio_info.invoke(optimized_query)
            
            # 3. Create the official ToolMessage so OpenAI doesn't crash!
            tool_message = ToolMessage(
                content=str(tool_output),
                tool_call_id=tool_call["id"],
                name=tool_call["name"]
            )
            
            # 4. The "Short-Circuit" Guardrail
            if "GUARDRAIL_TRIGGERED" in tool_output:
                logger.warning("⚠️ RAG INTERCEPT: No Pinecone data found. Short-circuiting LLM and returning to Supervisor.")
                return {"messages": [response, tool_message]}
            
            # 5. If data WAS found, call the RAG LLM one more time to generate the final portfolio answer
            logger.info("✅ Pinecone data found. Calling RAG LLM to generate final response...")
            final_messages = state["messages"] + [response, tool_message]
            final_response = await rag_llm.ainvoke(final_messages)
            
            return {"messages": [response, tool_message, final_response]}

    # If no tools were called at all, just return the AI's normal response
    return {"messages": [response]}

async def transactional_agent(state: AgentState):
    logger.info("🟢 ACTIVATED: Transactional Agent -> Preparing loan prediction model...")
    agent = llm.bind_tools([execute_loan_prediction])
    response = await agent.ainvoke([SystemMessage(content=TRANSACTIONAL_PROMPT)] + state["messages"])
    return {"messages": [response]}

async def out_of_bounds_node(state: AgentState):
    """Dynamically handles greetings or off-topic rejections."""
    logger.info("🛑 ACTIVATED: Out of Bounds Node -> Handling rejected off-topic query or greeting...")
    messages = [SystemMessage(content=OUT_OF_BOUNDS_PROMPT)] + state["messages"]
    response = await llm.ainvoke(messages)
    return {"messages": [response]}